#!/bin/bash
#
# http://github.com/mitchweaver/bin
#
# play a video on the root window
#

[ ! -f "$1" ] && exit 1

pkill -9 xwinwrap

#xwin="xwinwrap -ni -fdt -sh rectangle -un -b -nf -ov -fs -- "
xwin="xwinwrap -ov -ni -fs -nf -b -- "

mpv="mpv -wid WID --no-config --keepaspect=no --loop \
    --no-border --vd-lavc-fast --x11-bypass-compositor=no \
    --gapless-audio=yes --vo=xv --hwdec=auto --really-quiet \
    --name=mpvbg"

#mpv="mpv -vo x11 -wid WID --keepaspect=no --loop"



$xwin $mpv "$1" #> /dev/null 2>&1 &
echo $! > ${HOME}/.cache/mpvbg.pid
